xtask: Use the default `CMAKE_INSTALL_MODE`
The `ABS_SYMLINK` mode saves space, but does not work when running in a
container (using `container` attribute in GitHub Actions), due to
parts of the workspace mounted as different volumes, therefore causing
the following error:

```
-- Installing: /home/runner/work/bpf-linker/bpf-linker/llvm-install/include/llvm-c/BitWriter.h
Error: failed to move the target file /__w/bpf-linker/bpf-linker/llvm-build/lib/libLLVMDebugInfoLogicalView.a
to the location of the symlink /home/runner/work/bpf-linker/bpf-linker/llvm-install/lib/libLLVMDebugInfoLogicalView.a

Caused by:
    Invalid cross-device link (os error 18)
```

The default mode still does not exhaust the available disk space.